### ISSUE TITLE
Undefined index basicol

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/basicolor#1]
I get an error:

`Notice: Undefined index: basicol in theme_get_setting() (line 1461 of /var/www/html/core/includes/theme.inc).`

I believe you'll just need to fix this in color.inc:

`backdrop_add_js(array('color' => array('logo' => theme_get_setting('logo', 'basicol'))), 'setting');`

**Comment by docwilmot** [comment]
Fixed, thanks.
