### ISSUE TITLE
Undefined index: base, text.

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/basicolor#2]
When updating admin/appearance/settings/basicolor:

```
Notice: Undefined index: base in _color_rewrite_stylesheet()
Notice: Undefined index: text in _color_rewrite_stylesheet()
```

**Comment by herbdool** [comment]
In this function _color_rewrite_stylesheet it finds all the colours in the stylesheet. And if the color is not listed in the theme's color.inc it will first check for a "base" color (defined in color.inc) and then for "link" color and finally "text".

I didn't see "base" defined in bartik so maybe it's already got all the colors in the stylesheets defined. At any rate, setting "base" and "text" colours in color.inc fixes the notice.

**Comment by herbdool** [comment]
Looks like the same problem was cropping up in Drupal-land: https://www.drupal.org/node/789554

**Comment by herbdool** [comment]
It was bugging me why "base" wasn't listed in Bartik's color.inc and it was't complaining but it was for this theme. I've discovered it's because in Bartik all the hexes that are in colors.css are defined in color.inc so it never gets to live 451 in color.module where it tries to "Extrapolate from the base".

So I guess either add base or define all possible colours.

**Comment by docwilmot** [comment]
Thanks @herbdool. Should be fixed.
