### ISSUE TITLE
Add background color and background image to basicolor

### ISSUE THREAD

**Issue by SamStamport** [backdrop-contrib/basicolor#5]
Would it be possible to add functionality to the UI for basicolor to allow changing the background color of web pages? As I grow older I find that reading black fonts on white screens very tedious & tiring. If background color could be easily changed through the UI it would make using my site easier for us old folks.

Also, would it be possible to add functionality to optionally use an image as the background?

**Comment by docwilmot** [comment]
@ColumbiaBlooms I've added background color control and I'm testing it locally. Cant manage image backgrounds in his theme, sorry.
Please note that I am feeling like I've gotten carried away adding too many configurable elements and as such I'm considering simplifying this theme and removing some functionality. Its final version is still in flux, so I would be cautious using this in a production website until its got a published release.

**Comment by SamStamport** [comment]
Thanks so much for adding the background color. I'll check it out. Too bad about the image background option.

How will I know when there is a published release? I don't know much about github.

**Comment by SamStamport** [comment]
I downloaded your new version, but I don't see an option in the UI to change the background color. Maybe I got the wrong version ...

**Comment by docwilmot** [comment]
> How will I know when there is a published release? 

When we publish a release, it becomes available on BackdropCMS.org, so if you dont see it there, its not released yet

> How will I know when there is a published release? I don't know much about github.

Switch to a different color palette, save, then switch back; color module is a bit primitive, and it takes trickery to get changes to show up.

**Comment by SamStamport** [comment]
I switched to a different color set, saved the theme, then went back to my custom color set, but still do not see an option listed at /admin/appearance/settings/basicolor to change the overall background color of each page. What I'm hoping is possible is to change the default white background for text to something that's easier on the eyes.

**Comment by docwilmot** [comment]
It's there though. "Page background" and "text color". Try clearing caches or refreshing or save again.

**Comment by SamStamport** [comment]
Sorry to keep bothering you. Please see image I pasted. I cleared caches, ran cron, refreshed & saved, but it's still not there. 

How can I determine if I have the latest version of this theme. Maybe that's the problem.

![screencapture-localhost-8080-bd-admin-appearance-settings-basicolor-1487615883853](https://cloud.githubusercontent.com/assets/12977583/23137769/7eb7b43a-f769-11e6-83e5-f85217bb5965.png)

**Comment by docwilmot** [comment]
It might be that you dont have the latest code actually. [This line in color.inc](https://github.com/backdrop-contrib/basicolor/blob/master/color/color.inc#L10) defines the color picker for the page background. Its obviously there in GitHub.

**Comment by SamStamport** [comment]
Yea! It works. I did have an old version.

Sorry I had to bother you.

**Comment by klonos** [comment]
@ColumbiaBlooms in order to get the latest code of a GitHub project that doesn't have an official release:

![backdrop-contrib-get_latest_dev_version_from_github](https://cloud.githubusercontent.com/assets/2423362/23145910/5518dfb0-f826-11e6-9c6d-2fde73b9d6bf.png)

Maybe it's high time we got https://github.com/backdrop-ops/backdropcms.org/issues/236 sorted.

**Comment by SamStamport** [comment]
Thanks. You may close this report.

**Comment by klonos** [comment]
@ColumbiaBlooms 👍  ...issue already closed a couple of days ago by @docwilmot
