### ISSUE TITLE
Add iframe support for Google Calendar

### ISSUE THREAD

**Issue by SamStamport** [backdrop-contrib/basicolor#8]
Thanks to @Graham-72 embedding the Google Calendar into my site now works. He had me add 
`iframe {
height: 500px;
}`
at the end of style.css.

Could this code be added somehow to basicolor permanently?

**Comment by docwilmot** [comment]
Unfortunately Sam, I dont think so. That would mean every iframe ever embedded would get a height of 500px. The next guy with a 1000px calendar would  be complaining.

I cant think of a generic solution either. Will leave this open in case someone does.

**Comment by SamStamport** [comment]
Would it be possible to expose iframe height and max-width on the settings page for this sub-theme in the UI? What would be even cooler would be the ability to set height and max-width on a per node/page basis.

**Comment by Graham-72** [comment]
Since this problem is due to a setting in Basis, perhaps it should be fixed there? I am wondering whether this adversely affects all iFrames or is there a particular problem with the one from Google Calendar?

**Comment by SamStamport** [comment]
I don't know if this is a general problem with iFrame. I am not an expert iFrame person so I don't know how I would go about testing this.

**Comment by Graham-72** [comment]
I have now tested this with a different iFrame content with exactly the same problem. My conclusion is that it is wrong to have the style iframe height: auto in base.css in Basis. @wesruv please advise on this.
The alternative iframe content I have used is, I believe, only available to UK users. It is
```
<p><iframe height="450px" src="http://www.bbc.co.uk/weather/coast_and_sea/tide_tables/1/134a#tide-details" width="650px"></iframe></p>
```

**Comment by olafgrabienski** [comment]
I made a core issue regarding the iframe height: https://github.com/backdrop/backdrop-issues/issues/2622
